export enum Configuration {
  APP_PORT = "APP_PORT",
  APP_HOST = "APP_HOST",
  APP_PROTOCOL = "APP_PROTOCOL",
  APP_SESSION_SECRET = "APP_SESSION_SECRET",
  TYPEORM_CONNECTION = "TYPEORM_CONNECTION",
  TYPEORM_HOST = "TYPEORM_HOST",
  TYPEORM_PORT = "TYPEORM_PORT",
  TYPEORM_USERNAME = "TYPEORM_USERNAME",
  TYPEORM_PASSWORD = "TYPEORM_PASSWORD",
  TYPEORM_DATABASE = "TYPEORM_DATABASE",
}
